name = "itree"
version = "0.1.0"
defaultTargets = ["ITree"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "ITree"
globs = ["ITree.+"]
