name = "ctree"
version = "0.1.0"
defaultTargets = ["CTree"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0-rc3"

# [[require]]
# name = "Canonical"
# scope = "chasenorman"

[[lean_lib]]
name = "CTree"
globs = ["CTree.+"]
